[package]
name = "my_macro_derive"
version = "0.1.0"
authors = ["Fedor Sakharov <fedor.sakharov@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "0.15"
quote = "0.6"
proc-macro2 = "0.4"
